### ISSUE TITLE
JupyterLab support?

### ISSUE THREAD

**Issue by jtpio** [4Quant/DashIntro#4]
Dash works fine in the classic notebook thanks to https://github.com/4QuantOSS/DashIntro/commit/aaa59fa83b577f2a4351a02e57a7b91ce140e96e.

But not in JupyterLab, which could be related to the stricter policy regarding arbitrary evaluation of JavaScript and HTML in the notebook.

Maybe this could be achieved by creating a [JupyterLab extension](http://jupyterlab.readthedocs.io/en/stable/user/extensions.html)?

**Comment by kmader** [comment]
I haven't looked into it, but it shouldn't be too difficult

**Comment by jtpio** [comment]
Closing this one, as there seems to be some ongoing work for a JupyterLab extension: https://github.com/plotly/dash/issues/209#issuecomment-434006696

Let's keep an eye on it!
